### ISSUE TITLE
Configurable GOPATH

### ISSUE THREAD

**Issue by xaniasd** [andrewrothstein/ansible-go#1]
Hey, it would be nice if I could override the GOPATH environment variable from the default $HOME/go-work. Do you agree?

**Comment by andrewrothstein** [comment]
sounds reasonable. we'd have to migrate to a template and add a default var for the GOPATH subdir. do you feel comfortable making a pull request?

**Comment by xaniasd** [comment]
hehe, sure I'll give it a shot!

**Comment by andrewrothstein** [comment]
I tagged and release v1.0.5 of the role with your improvements to the galaxy. Thanks for your help!
