### ISSUE TITLE
GOBIN & GOPATH missing

### ISSUE THREAD

**Issue by 030** [andrewrothstein/ansible-go#11]
I am creating a PR right now

**Comment by 030** [comment]
With the introduction of the go modules it is also possible to drop the GOPATH and GOBIN.

**Comment by Kaurin** [comment]
I support the PR, but please check my comment in the PR discussion

**Comment by 030** [comment]
See comments related [PR](https://github.com/andrewrothstein/ansible-go/pull/12)
